version: '1'
name: "image-tags-api"

services:

  mysql:
    image: "mysql:8.0"
    container_name: mysql-itag
    environment:
      # Variable values are in .env file
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_USER_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    # Set the restart policy
    restart: unless-stopped

    volumes:
      - "mysql-image-tags:/var/lib/mysql/"
      - ./scripts/:/docker-entrypoint-initdb.d

  api-server:
    build: 
      context: .
    container_name: apiserver-itag
    environment:
      # Variable values are in .env file
      IMAGE_FOLDER: ${IMAGE_FOLDER}
      MYSQL_SERVER: mysql-itag
      MYSQL_USER_DATABASE: ${MYSQL_USER_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    # Set the restart policy
    restart: unless-stopped
    
    depends_on:
      - mysql

    expose:
      - 80

    ports:
      - "80:80"

    volumes:
      - ./images/:/usr/src/app/images/

volumes:
  mysql-image-tags:
